# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mark C. Magro
email: mcrmago@gmail.com
author: ""
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://markcmagro.com"
url: "https://markcmagro.github.io"

# Edit social-media.yml for social media IDs.
#github_username: markcmagro
#github_label: GitHub
#linkedin_username: markcmagro
#linkedin_label: LinkedIn
#youtube_username: markmagro
#youtube_label: YouTube

font_awesome: b96590e872.js

# Alternative for sorting pages:
#header_pages:
# - 02_about.markdown
# - 01_portfolio.markdown

include:
  - _pages
 
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - _pages/02_projects.markdown # disable projects page
  - _pages_/03_posts.markdown # disable posts page
  - _projects_ # remove all projects from projects page
  - _projects_/02_project2.markdown # remove a specific project
  - _posts/2024-02-26-post2.markdown # remove a specific post

collections:
  projects:
    output: true

disqus:
  shortname: optix-cuda-cmake-project-workflow
